### ISSUE TITLE
extracting anything but ping fails

### ISSUE THREAD

**Issue by egeldres** [RMonica/ros_kinfu#4] opened 2017-01-08 02:25 UTC
Hi, thank you for sharing this.
My build is having problems to extract the pointcloud.
I'm starting the server using:
roslaunch kinfu kinfu.launch
It launches well and start to build the tsdf, I can see the mesh image following the pose, using rviz without problems.

My requests works with ping only that is type: 0 or ping definition, I've used:
rostopic pub /kinfu1_request_topic kinfu_msgs/KinfuTsdfRequest "tsdf_header: {request_type: 0, request_id: 1, request_source_name: '/response'}"
using the full message and a node gives the same result.

[ INFO] [1483841989.524819173]: Avg frame time = 40.42 ms (24.74 fps)
[ INFO] [1483841989.545071821]: kinfu_output:
Received response with
0 cloud points
0 mesh cloud points
0 triangles
0 pixels
0 uint64 values
0 float32 values

[ INFO] [1483841990.936224604]: Avg frame time = 41.94 ms (23.84 fps)
[ INFO] [1483841992.327625026]: Avg frame time = 41.36 ms (24.18 fps)

I' think that is fine.

But when I'm sending request as:
rostopic pub /kinfu1_request_topic kinfu_msgs/KinfuTsdfRequest "tsdf_header: {request_type: 3, request_id: 1, request_source_name: '/response'}"
I've also tried using the full default message (request_reset: false, etc).
And build a node to avoid terminal fails.

[ INFO] [1483840839.782851318]: Avg frame time = 40.42 ms (24.74 fps)
[ INFO] [1483840841.142515084]: Avg frame time = 40.45 ms (24.72 fps)
[ INFO] [1483840841.526482931]: kinfu: Extract Cloud Worker started.
[ INFO] [1483840841.526525828]: kinfu: Locking kinfu...
[ INFO] [1483840841.607188089]: kinfu: Locked.
Extracting current volume...The old cube's metric origin was (0.000000, 0.000000, 0.000000).
The new cube's metric origin is now (0.017582, 0.000866, 0.002557).
Error: an illegal instruction was encountered /home/edu/catkin_ws/src/kinfu/pcl_kinfu_large_scale/kinfu_large_scale/src/cuda/extract.cu:400
[kinect_kinfu1-25] process has finished cleanly
log file: /home/edu/.ros/log/a6663ff4-d53d-11e6-9612-28c2dd10d8b1/kinect_kinfu1-25*.log

Not sure what exactly fails, it's supposed to be a cuda code, but I'm not sure if I need to send some kind of command or set a parameter before extracting the PointCloud or anything different than ping.

I hope someone can give me some hints on how to resolve my problem, many thanks in advance.

**Comment by RMonica** [comment] 2017-01-09 18:11
Hi egeldres.

That error means a crash in a CUDA kernel, the one called before line 400 in extract.cu: extractSliceKernel.
It seems that my rewrite of the extraction procedure is causing trouble for many people. \**sigh*\*

First of all:
- Check that you have the latest version of the CUDA toolkit and driver (old versions had problems with templates).
- Check that your video card is at least Compute Capability 3.0 (unlike original KinFu, my node does not support older video cards).

Unfortunately, extractSliceKernel uses the templated extraction class in templated_extract.cuh. It won't be easy to debug.

I recall I had some success with `cuda-memcheck` ([link](http://docs.nvidia.com/cuda/cuda-memcheck/)). Try adding
```
launch-prefix="cuda-memcheck "
```
to the node tag in the launch file. Maybe you will get more information. KinFu will run really slow - it is expected.

Otherwise, my usual approach is to comment out things until it stops crashing, and then try to guess why.

**Comment by egeldres** [comment] 2017-01-10 07:41
Hi RMonica,

thanks for your response, my cuda toolkit was failing so I corrected that and tried the cuda examples now working, but the Ros-Kinfu keeps crashing on the same stage. I'm using a Nvidia 960m whitch is 5.0 by the way.

I've tried to run the code now with the launch-prefix cuda memcheck, it was really slower but displayed some additional info
I will put it here in case somebody can see trough the lines,.


---
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://edu-G501JW:42270/

SUMMARY


PARAMETERS
 * /kinect1/depth_rectify_depth/interpolation: 0
 * /kinect1/depth_registered_rectify_depth/interpolation: 0
 * /kinect1/disparity_depth/max_range: 4.0
 * /kinect1/disparity_depth/min_range: 0.5
 * /kinect1/disparity_registered_hw/max_range: 4.0
 * /kinect1/disparity_registered_hw/min_range: 0.5
 * /kinect1/disparity_registered_sw/max_range: 4.0
 * /kinect1/disparity_registered_sw/min_range: 0.5
 * /kinect1/driver/depth_camera_info_url: 
 * /kinect1/driver/depth_frame_id: kinect1_depth_opt...
 * /kinect1/driver/depth_registration: False
 * /kinect1/driver/device_id: #1
 * /kinect1/driver/rgb_camera_info_url: 
 * /kinect1/driver/rgb_frame_id: kinect1_rgb_optic...
 * /kinect1/kinect1_nodelet_manager/num_worker_threads: 4
 * /kinect_kinfu1/autostart: True
 * /kinect_kinfu1/extract_known_points: True
 * /kinect_kinfu1/prefix_topic: /kinect1
 * /kinect_kinfu1/request_topic: /kinfu1_request_t...
 * /kinect_kinfu1/response_topic: /kinfu1_response_...
 * /rosdistro: jade
 * /rosversion: 1.11.20
NODES
  /kinect1/
    depth_metric (nodelet/nodelet)
    depth_metric_rect (nodelet/nodelet)
    depth_points (nodelet/nodelet)
    depth_rectify_depth (nodelet/nodelet)
    depth_registered_hw_metric_rect (nodelet/nodelet)
    depth_registered_metric (nodelet/nodelet)
    depth_registered_rectify_depth (nodelet/nodelet)
    depth_registered_sw_metric_rect (nodelet/nodelet)
    disparity_depth (nodelet/nodelet)
    disparity_registered_hw (nodelet/nodelet)
    disparity_registered_sw (nodelet/nodelet)
    driver (nodelet/nodelet)
    ir_rectify_ir (nodelet/nodelet)
    kinect1_nodelet_manager (nodelet/nodelet)
    points_xyzrgb_hw_registered (nodelet/nodelet)
    points_xyzrgb_sw_registered (nodelet/nodelet)
    register_depth_rgb (nodelet/nodelet)
    rgb_debayer (nodelet/nodelet)
    rgb_rectify_color (nodelet/nodelet)
    rgb_rectify_mono (nodelet/nodelet)
  /
    kinect1_base_link (tf2_ros/static_transform_publisher)
    kinect1_base_link1 (tf2_ros/static_transform_publisher)
    kinect1_base_link2 (tf2_ros/static_transform_publisher)
    kinect1_base_link3 (tf2_ros/static_transform_publisher)
    kinect_kinfu1 (kinfu/kinfu)
ROS_MASTER_URI=http://localhost:11311
core service [/rosout] found
process[kinect1/kinect1_nodelet_manager-1]: started with pid [27639]
process[kinect1/driver-2]: started with pid [27640]
process[kinect1/rgb_debayer-3]: started with pid [27641]
process[kinect1/rgb_rectify_mono-4]: started with pid [27643]
process[kinect1/rgb_rectify_color-5]: started with pid [27655]
process[kinect1/ir_rectify_ir-6]: started with pid [27665]
process[kinect1/depth_rectify_depth-7]: started with pid [27683]
[ INFO] [1484032849.355526402]: Initializing nodelet with 4 worker threads.
process[kinect1/depth_metric_rect-8]: started with pid [27699]
process[kinect1/depth_metric-9]: started with pid [27718]
process[kinect1/depth_points-10]: started with pid [27721]
process[kinect1/register_depth_rgb-11]: started with pid [27739]
process[kinect1/points_xyzrgb_sw_registered-12]: started with pid [27755]
process[kinect1/depth_registered_sw_metric_rect-13]: started with pid [27764]
process[kinect1/depth_registered_rectify_depth-14]: started with pid [27765]
process[kinect1/points_xyzrgb_hw_registered-15]: started with pid [27782]
process[kinect1/depth_registered_hw_metric_rect-16]: started with pid [27799]
process[kinect1/depth_registered_metric-17]: started with pid [27803]
process[kinect1/disparity_depth-18]: started with pid [27815]
process[kinect1/disparity_registered_sw-19]: started with pid [27826]
process[kinect1/disparity_registered_hw-20]: started with pid [27841]
process[kinect1_base_link-21]: started with pid [27848]
process[kinect1_base_link1-22]: started with pid [27853]
process[kinect1_base_link2-23]: started with pid [27862]
process[kinect1_base_link3-24]: started with pid [27874]
process[kinect_kinfu1-25]: started with pid [27883]
========= CUDA-MEMCHECK
[pcl::gpu::printShortCudaDeviceInfo] : Device 0:  "GeForce GTX 960M"  2048Mb, sm_50, 640 cores, Driver/Runtime ver.7.50/7.50
[ INFO] [1484032849.524002614]: Running KinFu without texture extraction
[ INFO] [1484032849.711463495]: kinfu_output: main thread started.
[ INFO] [1484032849.716965986]: --- CURRENT SETTINGS ---
[ INFO] [1484032849.717014761]: Volume size is set to 3.00 meters
[ INFO] [1484032849.717055856]: Volume will shift when the camera target point is farther than 1.50 meters from the volume center
[ INFO] [1484032849.717091185]: The target point is located at [0, 0, 1.80] in camera coordinates
[ INFO] [1484032849.717123471]: -
in reset function!
[ INFO] [1484032851.141159352]: Number devices connected: 1
[ INFO] [1484032851.141228681]: 1. device on bus 003:11 is a SensorV2 (2ae) from PrimeSense (45e) with serial id '0000000000000000'
[ INFO] [1484032851.141984134]: Searching for device with index = 1
[ INFO] [1484032851.175234726]: Opened 'SensorV2' on bus 3:11 with serial number '0000000000000000'
[ INFO] [1484032851.201215158]: rgb_frame_id = 'kinect1_rgb_optical_frame' 
[ INFO] [1484032851.201251943]: depth_frame_id = 'kinect1_depth_optical_frame' 
[ WARN] [1484032851.203925512]: Camera calibration file /home/edu/.ros/camera_info/rgb_0000000000000000.yaml not found.
[ WARN] [1484032851.203969967]: Using default parameters for RGB camera calibration.
[ WARN] [1484032851.204005160]: Camera calibration file /home/edu/.ros/camera_info/depth_0000000000000000.yaml not found.
[ WARN] [1484032851.204030373]: Using default parameters for IR camera calibration.
[ INFO] [1484032906.529417016]: Avg frame time = 1644.06 ms (0.61 fps)
[ INFO] [1484032935.648703395]: kinfu: Extract Cloud Worker started.
[ INFO] [1484032935.648773584]: kinfu: Locking kinfu...
[ INFO] [1484032938.632231075]: kinfu: Locked.
Extracting current volume...The old cube's metric origin was    (0.000000, 0.000000, 0.000000).
The new cube's metric origin is now (-0.001024, -0.001094, 0.001738).
========= Program hit cudaErrorIllegalAddress (error 77) due to "an illegal memory access was encountered" on CUDA API call to cudaDeviceSynchronize. 
Error: an illegal memory access was encountered	/home/edu/catkin_ws/src/kinfu/pcl_kinfu_large_scale/kinfu_large_scale/src/cuda/extract.cu:400
=========     Saved host backtrace up to driver entry point at error
=========     Host Frame:/usr/lib/x86_64-linux-gnu/libcuda.so.1 [0x2f31e3]
=========     Host Frame:/usr/local/cuda-7.5/lib64/libcudart.so.7.5 (cudaDeviceSynchronize + 0x166) [0x32cd6]
=========     Host Frame:/home/edu/catkin_ws/devel/lib/libKinfuLargeScaleCUDA.so (_ZN3pcl6device7kinfuLS19extractSliceAsCloudERKNS_3gpu7PtrStepI6short2EERK6float3PKNS2_7kinfuLS11tsdf_bufferEiiiNS2_5PtrSzI6float4EENSF_IfEENS3_IiEERi + 0x669) [0xe7ea]
=========     Host Frame:/home/edu/catkin_ws/devel/lib/libKinfuLargeScaleCPP.so (_ZNK3pcl3gpu7kinfuLS10TsdfVolume17fetchSliceAsCloudERNS0_11DeviceArrayINS_8PointXYZEEERNS3_IfEEPKNS1_11tsdf_bufferEiiiRNS0_13DeviceArray2DIiEERi + 0x14f) [0x249071]
=========     Host Frame:/home/edu/catkin_ws/devel/lib/libKinfuLargeScaleCPP.so (_ZNK3pcl3gpu7kinfuLS10TsdfVolume22fetchSliceAsPointCloudERNS0_11DeviceArrayINS_8PointXYZEEERNS3_IfEERNS0_13DeviceArray2DIiEEPKNS1_11tsdf_bufferEiii + 0x21a) [0x2494b4]
=========     Host Frame:/home/edu/catkin_ws/devel/lib/libKinfuLargeScaleCPP.so (_ZN3pcl3gpu7kinfuLS14CyclicalBuffer12performShiftEN5boost10shared_ptrINS1_10TsdfVolumeEEERKNS_8PointXYZEb + 0x234) [0x1daaa2]
=========     Host Frame:/home/edu/catkin_ws/devel/lib/libKinfuLargeScaleCPP.so (_ZN3pcl3gpu7kinfuLS14CyclicalBuffer13checkForShiftEN5boost10shared_ptrINS1_10TsdfVolumeEEERKN5Eigen9TransformIfLi3ELi2ELi0EEEdbbb + 0x1f4) [0x1d9fa8]
=========     Host Frame:/home/edu/catkin_ws/devel/lib/libKinfuLargeScaleCPP.so (_ZN3pcl3gpu7kinfuLS12KinfuTracker12extractWorldEv + 0xd1) [0x1ea45d]
=========     Host Frame:/home/edu/catkin_ws/devel/lib/kinfu/kinfu (_ZN20WorldDownloadManager18extractCloudWorkerEN5boost10shared_ptrIKN10kinfu_msgs17KinfuTsdfRequest_ISaIvEEEEE + 0x44f) [0x336b09]
=========     Host Frame:/home/edu/catkin_ws/devel/lib/kinfu/kinfu (_ZN20WorldDownloadManager13requestWorkerEN5boost10shared_ptrIKN10kinfu_msgs17KinfuTsdfRequest_ISaIvEEEEESt14_List_iteratorIPNS0_6threadEE + 0x17e) [0x335606]
=========     Host Frame:/home/edu/catkin_ws/devel/lib/kinfu/kinfu (_ZNK5boost4_mfi3mf2Iv20WorldDownloadManagerNS_10shared_ptrIKN10kinfu_msgs17KinfuTsdfRequest_ISaIvEEEEESt14_List_iteratorIPNS_6threadEEEclEPS2_S9_SD_ + 0x9c) [0x362026]
=========     Host Frame:/home/edu/catkin_ws/devel/lib/kinfu/kinfu (_ZN5boost3_bi5list3INS0_5valueIP20WorldDownloadManagerEENS2_INS_10shared_ptrIKN10kinfu_msgs17KinfuTsdfRequest_ISaIvEEEEEEENS2_ISt14_List_iteratorIPNS_6threadEEEEEclINS_4_mfi3mf2IvS3_SC_SH_EENS0_5list0EEEvNS0_4typeIvEERT_RT0_i + 0xa9) [0x361ed9]
=========     Host Frame:/home/edu/catkin_ws/devel/lib/kinfu/kinfu (_ZN5boost3_bi6bind_tIvNS_4_mfi3mf2Iv20WorldDownloadManagerNS_10shared_ptrIKN10kinfu_msgs17KinfuTsdfRequest_ISaIvEEEEESt14_List_iteratorIPNS_6threadEEEENS0_5list3INS0_5valueIPS4_EENSI_ISB_EENSI_ISF_EEEEEclEv + 0x4a) [0x361e12]
=========     Host Frame:/home/edu/catkin_ws/devel/lib/kinfu/kinfu (_ZN5boost6detail11thread_dataINS_3_bi6bind_tIvNS_4_mfi3mf2Iv20WorldDownloadManagerNS_10shared_ptrIKN10kinfu_msgs17KinfuTsdfRequest_ISaIvEEEEESt14_List_iteratorIPNS_6threadEEEENS2_5list3INS2_5valueIPS6_EENSK_ISD_EENSK_ISH_EEEEEEE3runEv + 0x1e) [0x361d42]
=========     Host Frame:/usr/lib/x86_64-linux-gnu/libboost_thread.so.1.55.0 [0xd09a]
=========     Host Frame:/lib/x86_64-linux-gnu/libpthread.so.0 [0x76aa]
=========     Host Frame:/lib/x86_64-linux-gnu/libc.so.6 (clone + 0x6d) [0x106eed]
=========
========= ERROR SUMMARY: 1 error
[kinect_kinfu1-25] process has finished cleanly
log file: /home/edu/.ros/log/49f3f45e-d705-11e6-84a4-94103eb91965/kinect_kinfu1-25*.log
-----

Many thanks in advance in case you can help me a little more

**Comment by RMonica** [comment] 2017-01-11 13:38
Hi egeldres.

I don't know.

Try updating to CUDA 8.0 (from NVidia website) and see if it fixes anything.

Also, you may try this patch:
[shift_tsdf_ptrstep.txt](https://github.com/RMonica/ros_kinfu/files/698981/shift_tsdf_ptrstep.txt)
(`git apply shift_tsdf_ptrstep.txt`)
Those risky pointer operations in shift_tsdf_pointer always worried me.

**Comment by egeldres** [comment] 2017-01-16 19:56
Hi RMonica,
many thanks for your feedback, I tried CUDA 8.0 on Ubuntu 16.04 but I think VTK6 is now difficulting my build, I was using 15.04 before.
Are you using Ubuntu 14.04 or another?

Best regards

**Comment by RMonica** [comment] 2017-01-17 16:00
Hi egeldres.

I'm using Ubuntu 16.04, but with isolated compilation (`catkin build`).

It seems that remove_vtk_definitions_hack.cmake is not working.
See if this patch helps.
[cmake_current_source_dir.patch.txt](https://github.com/RMonica/ros_kinfu/files/711584/cmake_current_source_dir.patch.txt)

**Comment by egeldres** [comment] 2017-01-18 04:33
Hi RMonica,

thanks for your answer, I was using catkin_make before, now with catkin build, there are no vtk6 issues (just related warning now) but Cuda shows the following failure during the build of kinfu .

/usr/bin/ld: /home/edu16/catkin_ws/devel/.private/kinfu/lib/kinfu/kinfu: hidden symbol `cudaMallocPitch' in /usr/local/cuda-8.0/lib64/libcudart_static.a(libcudart_static.a.o) is referenced by DSO
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [/home/edu16/catkin_ws/devel/.private/kinfu/lib/kinfu/kinfu] Error 1
make[1]: *** [CMakeFiles/kinfu.dir/all] Error 2
make: *** [all] Error 2

Just that package is failing with and without the suggested patch, and there are 2 small warnings, saying  io features related to pcap and png will be desabled, the log shows it's vtk6, but is just warning, the main complication it's cudaMallocPitch.

**Comment by RMonica** [comment] 2017-01-18 07:58
Hi egeldres.

Sometimes it happened to me, too.
I was never able to debug it, because as soon as I changed anything in the CMakeLists it just disappeared.
If you can reproduce the issue consistently, try to find a fix.

**Comment by egeldres** [comment] 2017-02-05 02:08
Hi RMonica,
thanks for the last update
https://github.com/RMonica/ros_kinfu/commit/f0393b838d4269c2875cc2887250f6f90481fed5
It fixed everything for me, now compiles fully without issues.

I'm having problems to get the full pointcloud, my request are just publishing 1 point per msg. But how to correctly use the project it's another thing. 
You can close this issue now, thanks a lot again.

**Comment by RMonica** [comment] 2017-02-07 08:30
Hi egeldres.

Only one point? That's not normal...

You are welcome.
I'm closing this issue, then.

**Closed as completed by RMonica** 2017-02-07 08:30 UTC
